package com.zenox.arrowmaze.features.authentication.components

import android.app.Activity
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.AccountCircle
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.zenox.arrowmaze.R
import com.zenox.arrowmaze.core.designsystem.components.ArrowMazeButton
import com.zenox.arrowmaze.core.designsystem.components.ButtonStyle
import kotlinx.coroutines.launch
import timber.log.Timber

/**
 * Encapsulates the Credential Manager Google Sign-In flow. Renders the
 * "Continue with Google" button and, when tapped, drives
 * `CredentialManager.getCredential(...)` with a [GetGoogleIdOption]
 * configured against the auto-generated `default_web_client_id` string
 * resource (the `google-services` plugin emits this from
 * `google-services.json`).
 *
 * On success the parsed [GoogleIdTokenCredential.idToken] is forwarded to
 * [onIdToken]. Errors are surfaced via [onError] with a human-readable
 * message — the caller typically shows a snackbar.
 *
 * The component uses the modern **Credentials API** (`androidx.credentials`)
 * rather than the deprecated `GoogleSignInClient` so it works on Android 13+
 * and participates in the unified Credential Manager UI.
 *
 * @param onIdToken  Invoked with the Google ID token on a successful sign-in.
 * @param onError    Invoked with a user-facing message when the flow fails.
 * @param enabled    Whether the button is tappable (false during loading).
 * @param isLoading  Whether to render the button in its loading state.
 */
@Composable
fun GoogleSignInButton(
    onIdToken: (String) -> Unit,
    onError: (String) -> Unit,
    modifier: Modifier = Modifier,
    enabled: Boolean = true,
    isLoading: Boolean = false,
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    // CRITICAL: CredentialManager.create() can throw on devices without
    // Google Play Services or with an outdated Play Services version.
    // We wrap it in runCatching so the Auth screen never crashes during
    // composition — the Google button simply shows an error message when
    // tapped if CredentialManager isn't available.
    val credentialManager = remember(context) {
        runCatching { CredentialManager.create(context) }
            .onFailure { Timber.w(it, "CredentialManager.create failed — Google sign-in disabled.") }
            .getOrNull()
    }

    // Web client ID is auto-generated by the google-services plugin from
    // the `oauth_client.client_type == 3` entry in google-services.json.
    val webClientId: String = stringResource(R.string.default_web_client_id)

    ArrowMazeButton(
        text = stringResource(R.string.auth_sign_in_google),
        onClick = {
            // If CredentialManager failed to create (no Play Services),
            // surface a user-friendly error instead of crashing.
            if (credentialManager == null) {
                onError("Google sign-in is not available on this device (Google Play Services required).")
                return@ArrowMazeButton
            }
            scope.launch {
                runCatching {
                    val googleIdOption = GetGoogleIdOption.Builder()
                        .setFilterByAuthorizedAccounts(false)
                        .setServerClientId(webClientId)
                        .setAutoSelectEnabled(false)
                        .build()
                    val request = GetCredentialRequest.Builder()
                        .addCredentialOption(googleIdOption)
                        .build()
                    // The Credential Manager suspend API takes an Activity
                    // (not a Context). LocalContext returns the Activity
                    // inside a Composable hosted by an ActivityComponent.
                    val activity = context as? Activity
                        ?: error("GoogleSignInButton must be hosted inside an Activity")
                    val result = credentialManager.getCredential(
                        context = activity,
                        request = request,
                    )
                    val credential = result.credential
                    val googleCredential = GoogleIdTokenCredential
                        .createFrom(credential.data)
                    googleCredential.idToken
                }
                    .onSuccess { idToken ->
                        Timber.d("Google ID token obtained (len=%d)", idToken.length)
                        onIdToken(idToken)
                    }
                    .onFailure { error ->
                        when (error) {
                            is NoCredentialException -> {
                                Timber.w(error, "No Google accounts on device.")
                                onError("No Google accounts found on this device.")
                            }
                            is GetCredentialException -> {
                                Timber.w(error, "Credential flow failed: %s", error.message)
                                onError("Google sign-in was cancelled or failed.")
                            }
                            else -> {
                                Timber.e(error, "Unexpected Google sign-in error.")
                                onError(error.message ?: "Google sign-in failed.")
                            }
                        }
                    }
            }
        },
        modifier = modifier,
        enabled = enabled,
        style = ButtonStyle.Glass,
        leadingIcon = Icons.Rounded.AccountCircle,
        isLoading = isLoading,
    )
}

